domn1995/dunet

src/Dunet/DiscriminatedUnionGenerator.cs
src/Dunet/RecordToGenerate.cs
src/Dunet/UnionSource.cs
test/Dunet.Test/Compiler/CompilationResult.cs
test/Dunet.Test/Compiler/Compile.cs
test/Dunet.Test/Compiler/GenerationResult.cs
test/Dunet.Test/NamespaceTests.cs
test/Dunet.Test/Runtime/AssemblyExtensions.cs
test/Dunet.Test/SwitchExpressionTests.cs

- Update generator logic to handle union definitions in global namespace.
- Add test for top level program.

Add support for top level programs.

---

src/Dunet/AccessibilityExtensions.cs
src/Dunet/DiscriminatedUnionGenerator.cs
src/Dunet/IdentifierExtensions.cs
src/Dunet/MatchMethodToGenerate.cs
src/Dunet/RecordToGenerate.cs
src/Dunet/UnionSource.cs
test/Dunet.Test/MatchMethodTests.cs
test/Dunet.Test/SwitchExpressionTests.cs

Adds generation of a dedicated match method for each union type.

Dedicated match method

---

Dunet.sln
test/Dunet.Integration/Dunet.Integration.csproj
test/Dunet.Integration/Match.cs
test/Dunet.Integration/SwitchExpression.cs
test/Dunet.Integration/Unions/INumberType.cs
test/Dunet.Integration/Unions/IShape.cs
test/Dunet.Integration/Usings.cs

Adds a basic integration test suite.

---

src/Dunet/DiscriminatedUnionGenerator.cs
src/Dunet/MatchMethodToGenerate.cs
src/Dunet/RecordToGenerate.cs
src/Dunet/SyntaxExtensions.cs
src/Dunet/UnionSource.cs
test/Dunet.Test/UnionGenerationTests.cs

Closes #14 
- Passes imports through from union declaration to generated code.
- Minor cleanup.

Adds support for complex types in union members

---

src/Dunet/SyntaxExtensions.cs
src/Dunet/UnionRecord/UnionRecord.cs
src/Dunet/UnionRecord/UnionRecordGenerator.cs
src/Dunet/UnionRecord/UnionRecordSource.cs
test/Dunet.Test/UnionInterface/GenerationTests.cs
test/Dunet.Test/UnionInterface/UnionInterfaceTests.cs
test/Dunet.Test/UnionRecord/GenerationTests.cs
test/Dunet.Test/UnionRecord/NamespaceTests.cs
test/Dunet.Test/UnionRecord/SwitchExpressionTests.cs
test/Dunet.Test/UnionRecord/UnionRecordTests.cs

- Adds support for partial record unions as per #17 
- Future PR will add match method generation.
- Future PR will add factory methods.

Partial record union support

---

src/Dunet/GenerateUnionRecord/UnionRecordSource.cs
src/Dunet/IdentifierExtensions.cs
test/Dunet.Test/GenerateUnionRecord/GenericGenerationTests.cs
test/Dunet.Test/GenerateUnionRecord/MatchMethodTests.cs

Address match methods from #17

Union record match method

---

Dunet.sln
Readme.md
samples/ExpressionCalculator/ExpressionCalculator.csproj
samples/ExpressionCalculator/Program.cs

Recursive expression calculator sample

---

src/GenerateUnionAttribute/UnionAttributeGenerator.cs
src/GenerateUnionAttribute/UnionAttributeSource.cs
src/GenerateUnionRecord/UnionRecordGenerator.cs
src/IsExternalInit.cs

* Closes #35
* Minor cleanup.
* Naming improvements.

Support multiple records with same name

---

test/GenerateUnionRecord/GenerationTests.cs
test/GenerateUnionRecord/NamespaceTests.cs

Add test for multiple unions with same name.

---

src/GenerateUnionRecord/UnionRecordSource.cs
test/GenerateUnionRecord/ImplicitConversionTests.cs

Implicit conversions

---

integration/GenerateUnionRecord/ImplicitConversion.cs
samples/OptionMonad/Program.cs
samples/PokemonClient/PokeClient.cs
samples/PokemonClient/Program.cs

- Adds implicit conversions integration test.
- Cleans up some samples to use implicit conversions.

Integrate implicit conversions.

---

integration/GenerateUnionRecord/Match.cs
test/GenerateUnionRecord/GenericGenerationTests.cs

Globalize integration and unit tests.

---

src/GenerateUnionRecord/UnionRecord.cs
src/GenerateUnionRecord/UnionRecordGenerator.cs
src/GenerateUnionRecord/UnionRecordSource.cs
src/SyntaxExtensions.cs
test/GenerateUnionRecord/NestedGenerationTests.cs

Support inner union classes

---

src/GenerateUnionExtensions/UnionExtensionsSource.cs
src/GenerateUnionRecord/StringBuilderExtensions.cs
src/GenerateUnionRecord/UnionRecord.cs
src/GenerateUnionRecord/UnionRecordGenerator.cs
src/SyntaxExtensions.cs
test/Compiler/Compile.cs
test/GenerateUnionExtensions/GenerationTests.cs
test/GenerateUnionExtensions/GenericGenerationTests.cs
test/GenerateUnionExtensions/GenericMatchAsyncMethodTests.cs
test/GenerateUnionExtensions/MatchAsyncMethodTests.cs
test/GenerateUnionExtensions/NestedGenerationTests.cs
test/GenerateUnionRecord/GenericGenerationTests.cs
test/Runtime/AssemblyExtensions.cs
test/UnionRecordTests.cs

Adds support for asynchronous matching on `Task`s of union types.
Closes #51

Async match support

---

samples/PokemonClient/Program.cs

Update web client sample with async match

---

src/GenerateUnionRecord/UnionRecordSource.cs
test/GenerateUnionRecord/ActionMatchMethodTests.cs
test/GenerateUnionRecord/GenericGenerationTests.cs

Action based match

---

src/Dunet.csproj

Closes #64 
Bump version and changelog to v1.4.0.

Release v1.4.0

---

src/GenerateUnionAttribute/UnionAttributeSource.cs
src/GenerateUnionExtensions/UnionExtensionsSource.cs
src/GenerateUnionRecord/UnionRecordSource.cs

Add pragma disables for CS1509

---

src/GenerateUnionExtensions/UnionExtensionsSource.cs
test/GenerateUnionExtensions/GenerationTests.cs
test/GenerateUnionExtensions/GenericGenerationTests.cs
test/GenerateUnionExtensions/GenericMatchAsyncMethodTests.cs
test/GenerateUnionExtensions/MatchAsyncMethodTests.cs
test/GenerateUnionExtensions/NestedGenerationTests.cs

Async match for actions

---

src/Dunet.csproj
src/GenerateUnionExtensions/UnionExtensionsSource.cs
src/GenerateUnionRecord/UnionRecordSource.cs
test/GenerateUnionExtensions/MatchSpecificUnionValueAsyncTests.cs
test/GenerateUnionRecord/MatchSpecificUnionValueTests.cs

Match on specific union values

---

Readme.md
src/Dunet.csproj
src/GenerateUnionRecord/RecordDeclarationSyntaxParser.cs
src/GenerateUnionRecord/UnionDeclaration.cs
src/GenerateUnionRecord/UnionGenerator.cs
src/GenerateUnionRecord/UnionSourceBuilder.cs
test/GenerateUnionRecord/GenerationTests.cs

Fix implicit conversion clash with required union properties

---

benchmark/Dunet.Benchmark/SourceGeneratorBenchmark.cs
src/UnionGeneration/UnionGenerator.cs

chore: remove nullable propogation and change naming

---

Readme.md
samples/Serialization/Program.cs

Update serialization sample
